### ISSUE TITLE
Update to Instant Client 19c

### ISSUE THREAD

**Issue by cjbj** [cjvirtucio87/todo-rscript-oracle#1]
When you update to Instant Client 19c you won't need to run ldconfig manually
https://github.com/cjvirtucio87/todo-rscript-oracle/blob/babeffe937b3ed52cfa7e61b7280717009be4d7e/.dockerfile/Dockerfile#L51-L52

See https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/19/Dockerfile and https://blogs.oracle.com/opal/oracle-instant-client-19c-for-linux-is-available

**Comment by cjvirtucio87** [comment]
This is good info, my company actually _just_ upgraded the db to 19 :)

**Comment by cjbj** [comment]
That's great.  Even if they hadn't updated, Oracle has "client"-to-"server" interoperability, so you can use older or newer versions of Instant Client with different versions of Oracle DB.  There is a sliding window of compatibility and, of course, not all features are available with older versions.

**Comment by cjvirtucio87** [comment]
[done|https://github.com/cjvirtucio87/todo-rscript-oracle/commit/dc0f973c36258c5ac79a39885175a4cabdd55ace].
